#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class Autosupport(Resource):
    """
    Get status of autosupport.

    Parameters:
    - id          : Identifier of the autosupport.
    - array_list  : List of arrays in the group with autosupport information.
    - array_count : Number of arrays in the group.
    - group_id    : Identifier for the group.
    - group_name  : Name of the group.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

class AutosupportList(Collection):
    resource = Autosupport
    resource_type = "autosupport"

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")
