#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#


from ...resource import Resource, Collection


class ClientCredential(Resource):
    """Credential that this device will trust.

    # Parameters
    id            : Identifier for the client credentials record.
    name          : Client name.
    client_id     : Uniqely identify this client, preferably uuid.
    secret        : Client secret corresponding to this client id and name.
    creation_time : Time when this client credentials was created.
    last_modified : Time when this client credentials was last modified.
    description   : Description of client.
    """


class ClientCredentialList(Collection):
    resource = ClientCredential
    resource_type = "client_credentials"
