#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class HealthCheck(Resource):
    """
    View the health of the group of arrays.

    Parameters:
    - id             : Identifier for the health check.
    - scope          : Scope at which the health check is to be run.
    - context        : Context for aggregating health check results.
    - on_demand      : Flag to indicate running the health checks and then report results.
    - array_id       : Identifier of the array to which this result belongs.
    - ctrlr_id       : Identifier of the controller to which this result belongs.
    - element_result : List of health check errors for a particular element.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")

class HealthCheckList(Collection):
    resource = HealthCheck
    resource_type = "health_checks"

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
