#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class KeyManager(Resource):
    """
    Key Manager stores encryption keys for the array volumes / dedupe domains.

    Parameters:
    - id          : Identifier for External Key Manager.
    - name        : Name of external key manager.
    - description : Description of external key manager.
    - hostname    : Hostname or IP Address for the External Key Manager.
    - port        : Port number for the External Key Manager.
    - protocol    : KMIP protocol supported by External Key Manager.
    - username    : External Key Manager username. String up to 255 printable characters.
    - password    : External Key Manager user password. String up to 255 printable characters.
    - active      : Whether the given key manager is active or not.
    - status      : Connection status of a given external key manager.
    - vendor      : KMIP vendor name.
    """

    def remove(self, passphrase=None):
        """
        Remove external key manager.

        Parameters:
        - id         : ID of the external key manager.
        - passphrase : Passphrase used to protect the master key, required during deletion of external key manager.
        """

        return self.collection.remove(self.id, passphrase)

    def migrate_keys(self):
        """
        Migrate volume encryption keys from source to destination.

        Parameters:
        - id : ID of the destination external key manager.
        """

        return self.collection.migrate_keys(self.id)

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

class KeyManagerList(Collection):
    resource = KeyManager
    resource_type = "key_managers"

    def remove(self, id, passphrase=None):
        """
        Remove external key manager.

        Parameters:
        - id         : ID of the external key manager.
        - passphrase : Passphrase used to protect the master key, required during deletion of external key manager.
        """

        return self._client.perform_resource_action(self.resource_type, id, 'remove', id=id, passphrase=passphrase)

    def migrate_keys(self, id):
        """
        Migrate volume encryption keys from source to destination.

        Parameters:
        - id : ID of the destination external key manager.
        """

        return self._client.perform_resource_action(self.resource_type, id, 'migrate_keys', id=id)

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")
