#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class ObjectLimit(Resource):
    """
    List the maximum limits and warning thresholds for number of objects in the storage group.

    Parameters:
    - id                : Identifier for the object limit.
    - object_type       : Unique ID of the object type.
    - object_type_name  : Name of object type.
    - scope_type        : Unique ID of the scope type for the object limit.
    - scope_type_name   : Scope type name for the object limit.
    - warning_threshold : Warning threshold for the object limit. A warning alert will be generated if the total number of objects in given scope crosses this threshold.
    - max_limit         : Total number of objects for a given scope is not allowed to cross this limit. Any user action attempting to create objects beyond this maximum limit will fail.
    - object_counts     : Current object counts for objects in given scope.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")

class ObjectLimitList(Collection):
    resource = ObjectLimit
    resource_type = "object_limits"

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
