#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class Stat(Resource):
    """
    Access generic stats interface via REST for internal testing.

    Parameters:
    - scope                  : Stat scope parameter to pass to stats reader.  Optional input attribute.
    - domain_id              : Stat domain_id to pass to stats reader.  Required input attribute with set_id if vol_id not used.
    - set_id                 : Stat set_id to pass to stats reader.  Required input attribute with domain_id if vol_id not used.
    - vol_ids                : A CSV list of REST vol-id to pass to stats reader.  Required input attribute if domain_id/set_id not used.
    - sensors                : Requested stats sensor list.  Optional input attribute.  Defaults to all sensors if not supplied.
    - startTime              : Retrieve stats with createTime greater than or equal to this time.  Optional input attribute.  Defaults to now if not supplied.
    - endTime                : Retrieve stats with createTime less than or equal to this time.  Optional input attribute.  Defaults to now if not supplied.
    - interval               : Retrieve stats with this time interval between values.  Typical use is 1, 60, or 3600 for per-second, per-minute, and per-hour stats.  Optional.  Defaults to 1 if not supplied.
    - cumulative             : Retrieve stat sensor cumulative data.
    - pool_id                : Stats summed for pool specified by this ID.  Optional input attribute.  Defaults to whole group if pool_id is not supplied.
    - array_name             : Retrieve stats from this array only.  Optional parameter.
    - sensor_data            : Response sensor data.
    - sensor_cumulative_data : Response sensor cumulative data.
    - vol_id                 : The REST ID of a volume.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")

class StatList(Collection):
    resource = Stat
    resource_type = "stats"

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
