#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#


from ...resource import Resource, Collection
from ...exceptions import NimOSAPIOperationUnsupported


class Support(Resource):
    """View and alter support-based parameters.

    # Parameters
    id            : Object identifier for the group.
    password_mode : Mode for support password.
    array_count   : Count of arrays for support password.
    array_list    : Details of support passwords for arrays.
    """

    def cycle(self):
        """Cycles the passwords for the group.

        # Parameters
        id : ID for the group.
        """

        return self._collection.cycle(
            self.id
        )

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")


class SupportList(Collection):
    resource = Support
    resource_type = "support"

    def cycle(self, id):
        """Cycles the passwords for the group.

        # Parameters
        id : ID for the group.
        """

        return self._client.perform_resource_action(
            self.resource_type,
            id,
            'cycle',
            id=id
        )

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
