#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#


from ...resource import Resource, Collection
from ...exceptions import NimOSAPIOperationUnsupported


class TrustedOauthIssuer(Resource):
    """Oauth Credential Issuers that this device will trust.

    # Parameters
    id       : Identifier for the trusted oauth issuer record.
    name     : Issuer ID string.
    jwks_url : The URL from which the device will download the public key set for signature verification.
    key_set  : List of public keys for verifying signatures.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")


class TrustedOauthIssuerList(Collection):
    resource = TrustedOauthIssuer
    resource_type = "trusted_oauth_issuers"

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
