#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class UninitializedArray(Resource):
    """
    Lists discovered arrays that are not members of any group and are in the same subnet.

    Parameters:
    - id                : Identifier for the interface.
    - serial            : Serial Number of the uninitialized array.
    - array_name        : Name of the uninitialized array.
    - model             : Model of the uninitialized array.
    - model_str         : Model description of the uninitialized array.
    - version           : Version of the uninitialized array.
    - ip_address        : Link local zero conf address of the uninitialized array.
    - zconf_ipaddrs     : List of link local zero conf address of the uninitialized array.
    - count_of_fc_ports : Number of Fibre Channel ports of the uninitialized array.
    - all_flash         : True if it is an All-Flash array, False otherwise.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")

class UninitializedArrayList(Collection):
    resource = UninitializedArray
    resource_type = "uninitialized_arrays"

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
