#
#   © Copyright 2020 Hewlett Packard Enterprise Development LP
#
#   This file was auto-generated by the Python SDK generator; DO NOT EDIT.
#

from ..resource import Resource, Collection
from ..exceptions import NimOSAPIOperationUnsupported

class VolumeFamily(Resource):
    """
    A volume family contains all the volumes, snapshots, and clones derived from and including a root volume.

    Parameters:
    - id                          : Identifier for the volume family.
    - pool_id                     : Identifier associated with the pool in the pools table.
    - pool_name                   : Name of the pool where the volume family resides.
    - blocksize                   : Size of blocks in the volume.
    - root_vol_name               : Volume family root volume name.
    - volumes                     : List of volumes.
    - vol_usage_compressed_bytes  : Sum of compressed bytes stored in the volumes of this family.
    - snap_usage_compressed_bytes : Sum of compressed bytes stored in the snapshots of this family.
    """

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")

class VolumeFamilyList(Collection):
    resource = VolumeFamily
    resource_type = "volume_families"

    def create(self, **kwargs):
        raise NimOSAPIOperationUnsupported("create operation not supported")

    def delete(self, **kwargs):
        raise NimOSAPIOperationUnsupported("delete operation not supported")

    def update(self, **kwargs):
        raise NimOSAPIOperationUnsupported("update operation not supported")
